Repository leginote/assembly-ts, pull requests merged in 2024-08, with the labels that each got.

#10 feat: add parliamentary diplomatic english dicionary pdf file
  parliamentary-diplomatic-english-dictionary.pdf
  src/constant/index.ts
Labels: documentation, good first issue

#15 ci: convert vitest provider to istanbul and remove effect
  package.json
  src/functional/callOpenApi.ts
  src/util/key.spec.ts
  src/util/key.ts
  vitest.config.mts
  yarn.lock
Labels: enhancement

#12 Feature/add getBillList function
  src/bill/getBillList.spec.ts
  src/bill/getBillList.ts
  src/bill/index.spec.ts
  src/bill/index.ts
  src/constant/index.ts
  src/types/callOpenApi.ts
Labels: enhancement

#22 Docs: Add CONTRIBUTING.md file (#21)
  CONTRIBUTING.md
Labels: documentation, enhancement
